// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: comments_sent.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createCommentSent = `-- name: CreateCommentSent :one

INSERT INTO comments_sent (pull_request_id, review_id, comment_id, type, file, category, anchor, parent_comment_id)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, pull_request_id, review_id, comment_id, type, file, category, anchor, parent_comment_id, created_at, resolved, applied
`

type CreateCommentSentParams struct {
	PullRequestID   int64
	ReviewID        pgtype.Int8
	CommentID       string
	Type            string
	File            pgtype.Text
	Category        pgtype.Text
	Anchor          pgtype.Text
	ParentCommentID pgtype.Text
}

// Comentarios publicados por PR (guía §3.3): idempotencia y actualización.
func (q *Queries) CreateCommentSent(ctx context.Context, arg CreateCommentSentParams) (CommentsSent, error) {
	row := q.db.QueryRow(ctx, createCommentSent,
		arg.PullRequestID,
		arg.ReviewID,
		arg.CommentID,
		arg.Type,
		arg.File,
		arg.Category,
		arg.Anchor,
		arg.ParentCommentID,
	)
	var i CommentsSent
	err := row.Scan(
		&i.ID,
		&i.PullRequestID,
		&i.ReviewID,
		&i.CommentID,
		&i.Type,
		&i.File,
		&i.Category,
		&i.Anchor,
		&i.ParentCommentID,
		&i.CreatedAt,
		&i.Resolved,
		&i.Applied,
	)
	return i, err
}

const getCommentSentByAnchor = `-- name: GetCommentSentByAnchor :one
SELECT id, pull_request_id, review_id, comment_id, type, file, category, anchor, parent_comment_id, created_at, resolved, applied FROM comments_sent
WHERE pull_request_id = $1 AND anchor = $2
`

type GetCommentSentByAnchorParams struct {
	PullRequestID int64
	Anchor        pgtype.Text
}

// Dedup de inline: huella file + categoría + ancla dentro del PR (§3.6).
func (q *Queries) GetCommentSentByAnchor(ctx context.Context, arg GetCommentSentByAnchorParams) (CommentsSent, error) {
	row := q.db.QueryRow(ctx, getCommentSentByAnchor, arg.PullRequestID, arg.Anchor)
	var i CommentsSent
	err := row.Scan(
		&i.ID,
		&i.PullRequestID,
		&i.ReviewID,
		&i.CommentID,
		&i.Type,
		&i.File,
		&i.Category,
		&i.Anchor,
		&i.ParentCommentID,
		&i.CreatedAt,
		&i.Resolved,
		&i.Applied,
	)
	return i, err
}

const getCommentsSentByPRAndType = `-- name: GetCommentsSentByPRAndType :many
SELECT id, pull_request_id, review_id, comment_id, type, file, category, anchor, parent_comment_id, created_at, resolved, applied FROM comments_sent
WHERE pull_request_id = $1 AND type = $2
ORDER BY id
`

type GetCommentsSentByPRAndTypeParams struct {
	PullRequestID int64
	Type          string
}

// Todos los comentarios de un tipo para el PR (el summary es único en la
// práctica; los inline pueden ser varios).
func (q *Queries) GetCommentsSentByPRAndType(ctx context.Context, arg GetCommentsSentByPRAndTypeParams) ([]CommentsSent, error) {
	rows, err := q.db.Query(ctx, getCommentsSentByPRAndType, arg.PullRequestID, arg.Type)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CommentsSent
	for rows.Next() {
		var i CommentsSent
		if err := rows.Scan(
			&i.ID,
			&i.PullRequestID,
			&i.ReviewID,
			&i.CommentID,
			&i.Type,
			&i.File,
			&i.Category,
			&i.Anchor,
			&i.ParentCommentID,
			&i.CreatedAt,
			&i.Resolved,
			&i.Applied,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateCommentSentCommentID = `-- name: UpdateCommentSentCommentID :one
UPDATE comments_sent
SET comment_id = $2
WHERE id = $1
RETURNING id, pull_request_id, review_id, comment_id, type, file, category, anchor, parent_comment_id, created_at, resolved, applied
`

type UpdateCommentSentCommentIDParams struct {
	ID        int64
	CommentID string
}

// El comentario se edita in-place: cambia su ID externo en el VCS.
func (q *Queries) UpdateCommentSentCommentID(ctx context.Context, arg UpdateCommentSentCommentIDParams) (CommentsSent, error) {
	row := q.db.QueryRow(ctx, updateCommentSentCommentID, arg.ID, arg.CommentID)
	var i CommentsSent
	err := row.Scan(
		&i.ID,
		&i.PullRequestID,
		&i.ReviewID,
		&i.CommentID,
		&i.Type,
		&i.File,
		&i.Category,
		&i.Anchor,
		&i.ParentCommentID,
		&i.CreatedAt,
		&i.Resolved,
		&i.Applied,
	)
	return i, err
}

const updateCommentsSentApplied = `-- name: UpdateCommentsSentApplied :exec
UPDATE comments_sent
SET applied = $2
WHERE id = $1
`

type UpdateCommentsSentAppliedParams struct {
	ID      int64
	Applied pgtype.Bool
}

// ¿La sugerencia terminó aplicada? Heurística por comentario inline (T5):
// con resolved alimenta la tasa FP (§6 F5) sin joins por huella.
func (q *Queries) UpdateCommentsSentApplied(ctx context.Context, arg UpdateCommentsSentAppliedParams) error {
	_, err := q.db.Exec(ctx, updateCommentsSentApplied, arg.ID, arg.Applied)
	return err
}

const updateCommentsSentResolved = `-- name: UpdateCommentsSentResolved :exec
UPDATE comments_sent
SET resolved = $2
WHERE id = $1
`

type UpdateCommentsSentResolvedParams struct {
	ID       int64
	Resolved pgtype.Bool
}

// Estado final del thread inline (§6 F5): el MetricsJob (T5) lo escribe al
// cierre del PR. Null = sin evaluar.
func (q *Queries) UpdateCommentsSentResolved(ctx context.Context, arg UpdateCommentsSentResolvedParams) error {
	_, err := q.db.Exec(ctx, updateCommentsSentResolved, arg.ID, arg.Resolved)
	return err
}
