// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: findings.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createFinding = `-- name: CreateFinding :one

INSERT INTO findings (review_id, file, line, severity, category, body, suggestion, source, verified)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
RETURNING id, review_id, file, line, severity, category, body, suggestion, source, verified, created_at
`

type CreateFindingParams struct {
	ReviewID   int64
	File       string
	Line       int32
	Severity   string
	Category   string
	Body       string
	Suggestion pgtype.Text
	Source     string
	Verified   pgtype.Bool
}

// Hallazgos (guía §3.3): FK a la corrida que los produjo.
// verified null hasta que el Verifier corre (F3); los SAST se publican sin
// verificación (§3.3).
func (q *Queries) CreateFinding(ctx context.Context, arg CreateFindingParams) (Finding, error) {
	row := q.db.QueryRow(ctx, createFinding,
		arg.ReviewID,
		arg.File,
		arg.Line,
		arg.Severity,
		arg.Category,
		arg.Body,
		arg.Suggestion,
		arg.Source,
		arg.Verified,
	)
	var i Finding
	err := row.Scan(
		&i.ID,
		&i.ReviewID,
		&i.File,
		&i.Line,
		&i.Severity,
		&i.Category,
		&i.Body,
		&i.Suggestion,
		&i.Source,
		&i.Verified,
		&i.CreatedAt,
	)
	return i, err
}

const listFindingsByPR = `-- name: ListFindingsByPR :many
SELECT f.id, f.review_id, f.file, f.line, f.severity, f.category, f.body, f.suggestion, f.source, f.verified, f.created_at
FROM findings f
JOIN reviews r ON r.id = f.review_id
WHERE r.pull_request_id = $1
ORDER BY f.id
`

// Atribución por corrida: todos los hallazgos de todas las corridas del PR.
func (q *Queries) ListFindingsByPR(ctx context.Context, pullRequestID int64) ([]Finding, error) {
	rows, err := q.db.Query(ctx, listFindingsByPR, pullRequestID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Finding
	for rows.Next() {
		var i Finding
		if err := rows.Scan(
			&i.ID,
			&i.ReviewID,
			&i.File,
			&i.Line,
			&i.Severity,
			&i.Category,
			&i.Body,
			&i.Suggestion,
			&i.Source,
			&i.Verified,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFindingsByReview = `-- name: ListFindingsByReview :many
SELECT id, review_id, file, line, severity, category, body, suggestion, source, verified, created_at FROM findings WHERE review_id = $1 ORDER BY id
`

func (q *Queries) ListFindingsByReview(ctx context.Context, reviewID int64) ([]Finding, error) {
	rows, err := q.db.Query(ctx, listFindingsByReview, reviewID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Finding
	for rows.Next() {
		var i Finding
		if err := rows.Scan(
			&i.ID,
			&i.ReviewID,
			&i.File,
			&i.Line,
			&i.Severity,
			&i.Category,
			&i.Body,
			&i.Suggestion,
			&i.Source,
			&i.Verified,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
