// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: llm_usage.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createLlmUsage = `-- name: CreateLlmUsage :one

INSERT INTO llm_usage (job_id, role, provider, model, tokens_in, tokens_out)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, job_id, role, provider, model, tokens_in, tokens_out, created_at
`

type CreateLlmUsageParams struct {
	JobID     pgtype.Int8
	Role      string
	Provider  string
	Model     string
	TokensIn  int32
	TokensOut int32
}

// Uso de LLM (guía §3.3): base de las métricas F5 y de los presupuestos (§9.6).
// Una fila por llamada LLM; job_id null en la prueba de conexión de settings.
func (q *Queries) CreateLlmUsage(ctx context.Context, arg CreateLlmUsageParams) (LlmUsage, error) {
	row := q.db.QueryRow(ctx, createLlmUsage,
		arg.JobID,
		arg.Role,
		arg.Provider,
		arg.Model,
		arg.TokensIn,
		arg.TokensOut,
	)
	var i LlmUsage
	err := row.Scan(
		&i.ID,
		&i.JobID,
		&i.Role,
		&i.Provider,
		&i.Model,
		&i.TokensIn,
		&i.TokensOut,
		&i.CreatedAt,
	)
	return i, err
}

const listLlmUsageByJob = `-- name: ListLlmUsageByJob :many
SELECT id, job_id, role, provider, model, tokens_in, tokens_out, created_at FROM llm_usage WHERE job_id = $1 ORDER BY id
`

func (q *Queries) ListLlmUsageByJob(ctx context.Context, jobID pgtype.Int8) ([]LlmUsage, error) {
	rows, err := q.db.Query(ctx, listLlmUsageByJob, jobID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []LlmUsage
	for rows.Next() {
		var i LlmUsage
		if err := rows.Scan(
			&i.ID,
			&i.JobID,
			&i.Role,
			&i.Provider,
			&i.Model,
			&i.TokensIn,
			&i.TokensOut,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const sumLlmUsageByDateRange = `-- name: SumLlmUsageByDateRange :one
SELECT COALESCE(SUM(tokens_in), 0)::bigint AS tokens_in,
       COALESCE(SUM(tokens_out), 0)::bigint AS tokens_out
FROM llm_usage
WHERE created_at >= $1 AND created_at < $2
`

type SumLlmUsageByDateRangeParams struct {
	CreatedAt   pgtype.Timestamptz
	CreatedAt_2 pgtype.Timestamptz
}

type SumLlmUsageByDateRangeRow struct {
	TokensIn  int64
	TokensOut int64
}

// Presupuestos (§9.6): tokens consumidos en la ventana [desde, hasta).
func (q *Queries) SumLlmUsageByDateRange(ctx context.Context, arg SumLlmUsageByDateRangeParams) (SumLlmUsageByDateRangeRow, error) {
	row := q.db.QueryRow(ctx, sumLlmUsageByDateRange, arg.CreatedAt, arg.CreatedAt_2)
	var i SumLlmUsageByDateRangeRow
	err := row.Scan(&i.TokensIn, &i.TokensOut)
	return i, err
}
