// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: llm_usage.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createLlmUsage = `-- name: CreateLlmUsage :one

INSERT INTO llm_usage (job_id, review_id, role, provider, model, tokens_in, tokens_out)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, job_id, role, provider, model, tokens_in, tokens_out, created_at, review_id
`

type CreateLlmUsageParams struct {
	JobID     pgtype.Int8
	ReviewID  pgtype.Int8
	Role      string
	Provider  string
	Model     string
	TokensIn  int32
	TokensOut int32
}

// Uso de LLM (guía §3.3): base de las métricas F5 y de los presupuestos (§9.6).
// Una fila por llamada LLM; job_id null en la prueba de conexión de settings;
// review_id null fuera de corrida (chat, index, pruebas — §6 F5).
func (q *Queries) CreateLlmUsage(ctx context.Context, arg CreateLlmUsageParams) (LlmUsage, error) {
	row := q.db.QueryRow(ctx, createLlmUsage,
		arg.JobID,
		arg.ReviewID,
		arg.Role,
		arg.Provider,
		arg.Model,
		arg.TokensIn,
		arg.TokensOut,
	)
	var i LlmUsage
	err := row.Scan(
		&i.ID,
		&i.JobID,
		&i.Role,
		&i.Provider,
		&i.Model,
		&i.TokensIn,
		&i.TokensOut,
		&i.CreatedAt,
		&i.ReviewID,
	)
	return i, err
}

const getAvgLlmTokensPerReview = `-- name: GetAvgLlmTokensPerReview :one
SELECT COALESCE(AVG(per_review.total_tokens), 0)::float8 AS avg_tokens_per_review,
       COUNT(*) AS reviews_counted
FROM (
    SELECT SUM(tokens_in + tokens_out) AS total_tokens
    FROM llm_usage
    WHERE review_id IS NOT NULL AND created_at >= $1
    GROUP BY review_id
) per_review
`

type GetAvgLlmTokensPerReviewRow struct {
	AvgTokensPerReview float64
	ReviewsCounted     int64
}

// Costo LLM medio por review (§6 F5): costo = tokens (in+out), sin precio
// por modelo modelado. Un grupo por review con linkage; las reviews sin
// usage no cuentan. El AVG es sobre totales por review, no por llamada.
// Ventana (T7): usos con created_at >= since — la misma convención del
// resumen de métricas (los outcomes se evalúan sobre filas en la ventana),
// así el endpoint /api/metrics es consistente en todas sus tasas.
func (q *Queries) GetAvgLlmTokensPerReview(ctx context.Context, since pgtype.Timestamptz) (GetAvgLlmTokensPerReviewRow, error) {
	row := q.db.QueryRow(ctx, getAvgLlmTokensPerReview, since)
	var i GetAvgLlmTokensPerReviewRow
	err := row.Scan(&i.AvgTokensPerReview, &i.ReviewsCounted)
	return i, err
}

const listLlmUsageByJob = `-- name: ListLlmUsageByJob :many
SELECT id, job_id, role, provider, model, tokens_in, tokens_out, created_at, review_id FROM llm_usage WHERE job_id = $1 ORDER BY id
`

func (q *Queries) ListLlmUsageByJob(ctx context.Context, jobID pgtype.Int8) ([]LlmUsage, error) {
	rows, err := q.db.Query(ctx, listLlmUsageByJob, jobID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []LlmUsage
	for rows.Next() {
		var i LlmUsage
		if err := rows.Scan(
			&i.ID,
			&i.JobID,
			&i.Role,
			&i.Provider,
			&i.Model,
			&i.TokensIn,
			&i.TokensOut,
			&i.CreatedAt,
			&i.ReviewID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const sumLlmUsageByDateRange = `-- name: SumLlmUsageByDateRange :one
SELECT COALESCE(SUM(tokens_in), 0)::bigint AS tokens_in,
       COALESCE(SUM(tokens_out), 0)::bigint AS tokens_out
FROM llm_usage
WHERE created_at >= $1 AND created_at < $2
`

type SumLlmUsageByDateRangeParams struct {
	CreatedAt   pgtype.Timestamptz
	CreatedAt_2 pgtype.Timestamptz
}

type SumLlmUsageByDateRangeRow struct {
	TokensIn  int64
	TokensOut int64
}

// Presupuestos (§9.6): tokens consumidos en la ventana [desde, hasta).
func (q *Queries) SumLlmUsageByDateRange(ctx context.Context, arg SumLlmUsageByDateRangeParams) (SumLlmUsageByDateRangeRow, error) {
	row := q.db.QueryRow(ctx, sumLlmUsageByDateRange, arg.CreatedAt, arg.CreatedAt_2)
	var i SumLlmUsageByDateRangeRow
	err := row.Scan(&i.TokensIn, &i.TokensOut)
	return i, err
}
