// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: llm_providers.sql

package store

import (
	"context"
)

const createLlmProvider = `-- name: CreateLlmProvider :one
INSERT INTO llm_providers (base_url, model, api_key, role, priority, enabled)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, base_url, model, api_key, role, priority, enabled, created_at, updated_at
`

type CreateLlmProviderParams struct {
	BaseUrl  string
	Model    string
	ApiKey   string
	Role     string
	Priority int32
	Enabled  bool
}

// api_key viaja cifrada AES-256-GCM en base64 (§9.2).
func (q *Queries) CreateLlmProvider(ctx context.Context, arg CreateLlmProviderParams) (LlmProvider, error) {
	row := q.db.QueryRow(ctx, createLlmProvider,
		arg.BaseUrl,
		arg.Model,
		arg.ApiKey,
		arg.Role,
		arg.Priority,
		arg.Enabled,
	)
	var i LlmProvider
	err := row.Scan(
		&i.ID,
		&i.BaseUrl,
		&i.Model,
		&i.ApiKey,
		&i.Role,
		&i.Priority,
		&i.Enabled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteLlmProvider = `-- name: DeleteLlmProvider :exec
DELETE FROM llm_providers WHERE id = $1
`

func (q *Queries) DeleteLlmProvider(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteLlmProvider, id)
	return err
}

const getLlmProvider = `-- name: GetLlmProvider :one
SELECT id, base_url, model, api_key, role, priority, enabled, created_at, updated_at FROM llm_providers WHERE id = $1
`

func (q *Queries) GetLlmProvider(ctx context.Context, id int64) (LlmProvider, error) {
	row := q.db.QueryRow(ctx, getLlmProvider, id)
	var i LlmProvider
	err := row.Scan(
		&i.ID,
		&i.BaseUrl,
		&i.Model,
		&i.ApiKey,
		&i.Role,
		&i.Priority,
		&i.Enabled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listEnabledLlmProvidersByRole = `-- name: ListEnabledLlmProvidersByRole :many
SELECT id, base_url, model, api_key, role, priority, enabled, created_at, updated_at FROM llm_providers
WHERE role = $1 AND enabled
ORDER BY priority, id
`

// Cadena de failover del rol: solo habilitados, en orden de prioridad (§3.3).
func (q *Queries) ListEnabledLlmProvidersByRole(ctx context.Context, role string) ([]LlmProvider, error) {
	rows, err := q.db.Query(ctx, listEnabledLlmProvidersByRole, role)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []LlmProvider
	for rows.Next() {
		var i LlmProvider
		if err := rows.Scan(
			&i.ID,
			&i.BaseUrl,
			&i.Model,
			&i.ApiKey,
			&i.Role,
			&i.Priority,
			&i.Enabled,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLlmProviders = `-- name: ListLlmProviders :many

SELECT id, base_url, model, api_key, role, priority, enabled, created_at, updated_at FROM llm_providers ORDER BY priority, id
`

// Proveedores LLM (guía §3.3): CRUD de settings + cadena de failover por rol.
// Orden estable por (priority, id): el orden de failover dentro del rol (§3.3).
func (q *Queries) ListLlmProviders(ctx context.Context) ([]LlmProvider, error) {
	rows, err := q.db.Query(ctx, listLlmProviders)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []LlmProvider
	for rows.Next() {
		var i LlmProvider
		if err := rows.Scan(
			&i.ID,
			&i.BaseUrl,
			&i.Model,
			&i.ApiKey,
			&i.Role,
			&i.Priority,
			&i.Enabled,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateLlmProvider = `-- name: UpdateLlmProvider :one
UPDATE llm_providers
SET base_url = $2,
    model = $3,
    api_key = $4,
    role = $5,
    priority = $6,
    enabled = $7,
    updated_at = now()
WHERE id = $1
RETURNING id, base_url, model, api_key, role, priority, enabled, created_at, updated_at
`

type UpdateLlmProviderParams struct {
	ID       int64
	BaseUrl  string
	Model    string
	ApiKey   string
	Role     string
	Priority int32
	Enabled  bool
}

func (q *Queries) UpdateLlmProvider(ctx context.Context, arg UpdateLlmProviderParams) (LlmProvider, error) {
	row := q.db.QueryRow(ctx, updateLlmProvider,
		arg.ID,
		arg.BaseUrl,
		arg.Model,
		arg.ApiKey,
		arg.Role,
		arg.Priority,
		arg.Enabled,
	)
	var i LlmProvider
	err := row.Scan(
		&i.ID,
		&i.BaseUrl,
		&i.Model,
		&i.ApiKey,
		&i.Role,
		&i.Priority,
		&i.Enabled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
