// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package store

import (
	"database/sql/driver"
	"fmt"

	"github.com/jackc/pgx/v5/pgtype"
)

type RiverJobState string

const (
	RiverJobStateAvailable RiverJobState = "available"
	RiverJobStateCancelled RiverJobState = "cancelled"
	RiverJobStateCompleted RiverJobState = "completed"
	RiverJobStateDiscarded RiverJobState = "discarded"
	RiverJobStatePending   RiverJobState = "pending"
	RiverJobStateRetryable RiverJobState = "retryable"
	RiverJobStateRunning   RiverJobState = "running"
	RiverJobStateScheduled RiverJobState = "scheduled"
)

func (e *RiverJobState) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = RiverJobState(s)
	case string:
		*e = RiverJobState(s)
	default:
		return fmt.Errorf("unsupported scan type for RiverJobState: %T", src)
	}
	return nil
}

type NullRiverJobState struct {
	RiverJobState RiverJobState
	Valid         bool // Valid is true if RiverJobState is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullRiverJobState) Scan(value interface{}) error {
	if value == nil {
		ns.RiverJobState, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.RiverJobState.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullRiverJobState) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.RiverJobState), nil
}

type CommentsSent struct {
	ID              int64
	PullRequestID   int64
	ReviewID        pgtype.Int8
	CommentID       string
	Type            string
	File            pgtype.Text
	Category        pgtype.Text
	Anchor          pgtype.Text
	ParentCommentID pgtype.Text
	CreatedAt       pgtype.Timestamptz
}

type Finding struct {
	ID         int64
	ReviewID   int64
	File       string
	Line       int32
	Severity   string
	Category   string
	Body       string
	Suggestion pgtype.Text
	Source     string
	Verified   pgtype.Bool
	CreatedAt  pgtype.Timestamptz
}

type LlmProvider struct {
	ID        int64
	BaseUrl   string
	Model     string
	ApiKey    string
	Role      string
	Priority  int32
	Enabled   bool
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}

type LlmUsage struct {
	ID        int64
	JobID     pgtype.Int8
	Role      string
	Provider  string
	Model     string
	TokensIn  int32
	TokensOut int32
	CreatedAt pgtype.Timestamptz
}

type PullRequest struct {
	ID           int64
	RepositoryID int64
	Number       int64
	Author       string
	State        string
	HeadSha      string
	BaseRef      string
	BaseSha      string
	MergedAt     pgtype.Timestamptz
	CreatedAt    pgtype.Timestamptz
	UpdatedAt    pgtype.Timestamptz
}

type RepoIndex struct {
	ID             int64
	RepositoryID   int64
	File           string
	Symbol         string
	Kind           string
	StartLine      int32
	EndLine        int32
	Embedding      string
	EmbeddingModel string
	Dims           int32
	Imports        []string
	FileHash       string
	CreatedAt      pgtype.Timestamptz
	UpdatedAt      pgtype.Timestamptz
}

type Repository struct {
	ID            int64
	Vcs           string
	ExternalID    int64
	Owner         string
	Name          string
	WebhookSecret pgtype.Text
	SecretToken   pgtype.Text
	ApiToken      pgtype.Text
	BaseUrl       pgtype.Text
	DeployKey     pgtype.Text
	Enabled       bool
	ReviewDrafts  bool
	Language      string
	ChatOrgOnly   bool
	CreatedAt     pgtype.Timestamptz
	UpdatedAt     pgtype.Timestamptz
}

type Review struct {
	ID            int64
	PullRequestID int64
	HeadSha       string
	BaseSha       string
	Summary       string
	Walkthrough   string
	Mermaid       string
	Status        string
	CreatedAt     pgtype.Timestamptz
	UpdatedAt     pgtype.Timestamptz
}

type RiverJob struct {
	ID           int64
	State        RiverJobState
	Attempt      int16
	MaxAttempts  int16
	AttemptedAt  pgtype.Timestamptz
	CreatedAt    pgtype.Timestamptz
	FinalizedAt  pgtype.Timestamptz
	ScheduledAt  pgtype.Timestamptz
	Priority     int16
	Args         []byte
	AttemptedBy  []string
	Errors       [][]byte
	Kind         string
	Metadata     []byte
	Queue        string
	Tags         []string
	UniqueKey    []byte
	UniqueStates pgtype.Bits
}

type RiverLeader struct {
	ElectedAt pgtype.Timestamptz
	ExpiresAt pgtype.Timestamptz
	LeaderID  string
	Name      string
}

type RiverMigration struct {
	ID        int64
	CreatedAt pgtype.Timestamptz
	Version   int64
}

type RiverNotification struct {
	ID        int64
	CreatedAt pgtype.Timestamptz
	Payload   string
	Topic     string
}

type RiverQueue struct {
	Name      string
	CreatedAt pgtype.Timestamptz
	Metadata  []byte
	PausedAt  pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}

type Session struct {
	ID        int64
	TokenHash string
	UserID    int64
	ExpiresAt pgtype.Timestamptz
	CreatedAt pgtype.Timestamptz
}

type User struct {
	ID                 int64
	Username           string
	Role               string
	PasswordHash       string
	MustChangePassword bool
	Disabled           bool
	CreatedAt          pgtype.Timestamptz
	UpdatedAt          pgtype.Timestamptz
}

type WebhookDelivery struct {
	ID         int64
	Vcs        string
	DeliveryID string
	CreatedAt  pgtype.Timestamptz
}
