// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: pull_requests.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getPullRequestByRepoNumber = `-- name: GetPullRequestByRepoNumber :one
SELECT id, repository_id, number, author, state, head_sha, base_ref, base_sha, merged_at, created_at, updated_at FROM pull_requests WHERE repository_id = $1 AND number = $2
`

type GetPullRequestByRepoNumberParams struct {
	RepositoryID int64
	Number       int64
}

func (q *Queries) GetPullRequestByRepoNumber(ctx context.Context, arg GetPullRequestByRepoNumberParams) (PullRequest, error) {
	row := q.db.QueryRow(ctx, getPullRequestByRepoNumber, arg.RepositoryID, arg.Number)
	var i PullRequest
	err := row.Scan(
		&i.ID,
		&i.RepositoryID,
		&i.Number,
		&i.Author,
		&i.State,
		&i.HeadSha,
		&i.BaseRef,
		&i.BaseSha,
		&i.MergedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listOpenPullRequestsByRepo = `-- name: ListOpenPullRequestsByRepo :many
SELECT id, repository_id, number, author, state, head_sha, base_ref, base_sha, merged_at, created_at, updated_at FROM pull_requests
WHERE repository_id = $1 AND state = 'open'
ORDER BY number DESC
`

func (q *Queries) ListOpenPullRequestsByRepo(ctx context.Context, repositoryID int64) ([]PullRequest, error) {
	rows, err := q.db.Query(ctx, listOpenPullRequestsByRepo, repositoryID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PullRequest
	for rows.Next() {
		var i PullRequest
		if err := rows.Scan(
			&i.ID,
			&i.RepositoryID,
			&i.Number,
			&i.Author,
			&i.State,
			&i.HeadSha,
			&i.BaseRef,
			&i.BaseSha,
			&i.MergedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updatePullRequestState = `-- name: UpdatePullRequestState :one
UPDATE pull_requests
SET state = $2,
    merged_at = $3,
    updated_at = now()
WHERE id = $1
RETURNING id, repository_id, number, author, state, head_sha, base_ref, base_sha, merged_at, created_at, updated_at
`

type UpdatePullRequestStateParams struct {
	ID       int64
	State    string
	MergedAt pgtype.Timestamptz
}

// Close/merge/reopen: el merge es un close con merged_at registrada (§3.3);
// un reopen pasa merged_at null.
func (q *Queries) UpdatePullRequestState(ctx context.Context, arg UpdatePullRequestStateParams) (PullRequest, error) {
	row := q.db.QueryRow(ctx, updatePullRequestState, arg.ID, arg.State, arg.MergedAt)
	var i PullRequest
	err := row.Scan(
		&i.ID,
		&i.RepositoryID,
		&i.Number,
		&i.Author,
		&i.State,
		&i.HeadSha,
		&i.BaseRef,
		&i.BaseSha,
		&i.MergedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertPullRequest = `-- name: UpsertPullRequest :one

INSERT INTO pull_requests (repository_id, number, author, state, head_sha, base_ref, base_sha, merged_at, created_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
ON CONFLICT (repository_id, number) DO UPDATE
SET author = EXCLUDED.author,
    state = EXCLUDED.state,
    head_sha = EXCLUDED.head_sha,
    base_ref = EXCLUDED.base_ref,
    base_sha = EXCLUDED.base_sha,
    merged_at = COALESCE(EXCLUDED.merged_at, pull_requests.merged_at),
    updated_at = now()
RETURNING id, repository_id, number, author, state, head_sha, base_ref, base_sha, merged_at, created_at, updated_at
`

type UpsertPullRequestParams struct {
	RepositoryID int64
	Number       int64
	Author       string
	State        string
	HeadSha      string
	BaseRef      string
	BaseSha      string
	MergedAt     pgtype.Timestamptz
	CreatedAt    pgtype.Timestamptz
}

// PRs observados (guía §3.3): clave natural repo + número/iid en el VCS.
// Upsert idempotente por webhook: el mismo PR re-procesado no duplica fila.
// merged_at usa COALESCE: un evento posterior sin merge no borra el registro.
// created_at es la fecha del PR en el VCS: se mantiene la primera (§3.3).
func (q *Queries) UpsertPullRequest(ctx context.Context, arg UpsertPullRequestParams) (PullRequest, error) {
	row := q.db.QueryRow(ctx, upsertPullRequest,
		arg.RepositoryID,
		arg.Number,
		arg.Author,
		arg.State,
		arg.HeadSha,
		arg.BaseRef,
		arg.BaseSha,
		arg.MergedAt,
		arg.CreatedAt,
	)
	var i PullRequest
	err := row.Scan(
		&i.ID,
		&i.RepositoryID,
		&i.Number,
		&i.Author,
		&i.State,
		&i.HeadSha,
		&i.BaseRef,
		&i.BaseSha,
		&i.MergedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
