// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: pull_requests.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getPullRequest = `-- name: GetPullRequest :one
SELECT id, repository_id, number, author, state, head_sha, base_ref, base_sha, merged_at, created_at, updated_at FROM pull_requests WHERE id = $1
`

// Por ID: el pipeline de review resuelve la fila desde el job (§3.6.1.3 —
// re-chequeo de la identidad de la corrida contra el estado actual del PR).
func (q *Queries) GetPullRequest(ctx context.Context, id int64) (PullRequest, error) {
	row := q.db.QueryRow(ctx, getPullRequest, id)
	var i PullRequest
	err := row.Scan(
		&i.ID,
		&i.RepositoryID,
		&i.Number,
		&i.Author,
		&i.State,
		&i.HeadSha,
		&i.BaseRef,
		&i.BaseSha,
		&i.MergedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPullRequestByRepoNumber = `-- name: GetPullRequestByRepoNumber :one
SELECT id, repository_id, number, author, state, head_sha, base_ref, base_sha, merged_at, created_at, updated_at FROM pull_requests WHERE repository_id = $1 AND number = $2
`

type GetPullRequestByRepoNumberParams struct {
	RepositoryID int64
	Number       int64
}

func (q *Queries) GetPullRequestByRepoNumber(ctx context.Context, arg GetPullRequestByRepoNumberParams) (PullRequest, error) {
	row := q.db.QueryRow(ctx, getPullRequestByRepoNumber, arg.RepositoryID, arg.Number)
	var i PullRequest
	err := row.Scan(
		&i.ID,
		&i.RepositoryID,
		&i.Number,
		&i.Author,
		&i.State,
		&i.HeadSha,
		&i.BaseRef,
		&i.BaseSha,
		&i.MergedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listOpenPullRequestsByRepo = `-- name: ListOpenPullRequestsByRepo :many
SELECT id, repository_id, number, author, state, head_sha, base_ref, base_sha, merged_at, created_at, updated_at FROM pull_requests
WHERE repository_id = $1 AND state = 'open'
ORDER BY number DESC
`

func (q *Queries) ListOpenPullRequestsByRepo(ctx context.Context, repositoryID int64) ([]PullRequest, error) {
	rows, err := q.db.Query(ctx, listOpenPullRequestsByRepo, repositoryID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PullRequest
	for rows.Next() {
		var i PullRequest
		if err := rows.Scan(
			&i.ID,
			&i.RepositoryID,
			&i.Number,
			&i.Author,
			&i.State,
			&i.HeadSha,
			&i.BaseRef,
			&i.BaseSha,
			&i.MergedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPullRequestsWithLatestReview = `-- name: ListPullRequestsWithLatestReview :many
SELECT pr.id,
       pr.repository_id,
       pr.number,
       pr.author,
       pr.state,
       pr.head_sha,
       pr.base_ref,
       pr.updated_at,
       repo.owner   AS repo_owner,
       repo.name    AS repo_name,
       repo.vcs     AS repo_vcs,
       COALESCE(r.id, 0)                            AS review_id,
       COALESCE(r.status, '')                       AS review_status,
       COALESCE(r.created_at, to_timestamp(0))      AS review_created_at,
       COUNT(f.id) FILTER (WHERE f.severity = 'high')   AS high,
       COUNT(f.id) FILTER (WHERE f.severity = 'medium') AS medium,
       COUNT(f.id) FILTER (WHERE f.severity = 'low')    AS low
FROM pull_requests pr
JOIN repositories repo ON repo.id = pr.repository_id
LEFT JOIN LATERAL (
    SELECT id, status, created_at
    FROM reviews
    WHERE pull_request_id = pr.id
    ORDER BY id DESC
    LIMIT 1
) r ON true
LEFT JOIN findings f ON f.review_id = r.id
GROUP BY pr.id, repo.id, r.id, r.status, r.created_at
ORDER BY pr.updated_at DESC
`

type ListPullRequestsWithLatestReviewRow struct {
	ID              int64
	RepositoryID    int64
	Number          int64
	Author          string
	State           string
	HeadSha         string
	BaseRef         string
	UpdatedAt       pgtype.Timestamptz
	RepoOwner       string
	RepoName        string
	RepoVcs         string
	ReviewID        int64
	ReviewStatus    string
	ReviewCreatedAt pgtype.Timestamptz
	High            int64
	Medium          int64
	Low             int64
}

// Listado del dashboard (guía §6 F3): TODOS los PRs — los cerrados conservan
// valor de auditoría — con su última corrida y el conteo de hallazgos de esa
// corrida por severidad. El LATERAL trae la review más reciente (el id es
// monotónico: ORDER BY id DESC es estable) y el COUNT con FILTER se resuelve
// en la misma query: una sola ida a la BD, sin N+1.
//
// Los COALESCE existen por una limitación de sqlc: no infiere nullabilidad a
// través de LEFT JOIN LATERAL y generaría int64/string que revientan al
// escanear el NULL real de un PR sin corridas. El sentinel es review_id = 0
// (review_id/status/created_at interpolados): el handler lo mapea a
// latest_review: null.
func (q *Queries) ListPullRequestsWithLatestReview(ctx context.Context) ([]ListPullRequestsWithLatestReviewRow, error) {
	rows, err := q.db.Query(ctx, listPullRequestsWithLatestReview)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPullRequestsWithLatestReviewRow
	for rows.Next() {
		var i ListPullRequestsWithLatestReviewRow
		if err := rows.Scan(
			&i.ID,
			&i.RepositoryID,
			&i.Number,
			&i.Author,
			&i.State,
			&i.HeadSha,
			&i.BaseRef,
			&i.UpdatedAt,
			&i.RepoOwner,
			&i.RepoName,
			&i.RepoVcs,
			&i.ReviewID,
			&i.ReviewStatus,
			&i.ReviewCreatedAt,
			&i.High,
			&i.Medium,
			&i.Low,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updatePullRequestState = `-- name: UpdatePullRequestState :one
UPDATE pull_requests
SET state = $2,
    merged_at = $3,
    updated_at = now()
WHERE id = $1
RETURNING id, repository_id, number, author, state, head_sha, base_ref, base_sha, merged_at, created_at, updated_at
`

type UpdatePullRequestStateParams struct {
	ID       int64
	State    string
	MergedAt pgtype.Timestamptz
}

// Close/merge/reopen: el merge es un close con merged_at registrada (§3.3);
// un reopen pasa merged_at null.
func (q *Queries) UpdatePullRequestState(ctx context.Context, arg UpdatePullRequestStateParams) (PullRequest, error) {
	row := q.db.QueryRow(ctx, updatePullRequestState, arg.ID, arg.State, arg.MergedAt)
	var i PullRequest
	err := row.Scan(
		&i.ID,
		&i.RepositoryID,
		&i.Number,
		&i.Author,
		&i.State,
		&i.HeadSha,
		&i.BaseRef,
		&i.BaseSha,
		&i.MergedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertPullRequest = `-- name: UpsertPullRequest :one

INSERT INTO pull_requests (repository_id, number, author, state, head_sha, base_ref, base_sha, merged_at, created_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
ON CONFLICT (repository_id, number) DO UPDATE
SET author = EXCLUDED.author,
    state = EXCLUDED.state,
    head_sha = EXCLUDED.head_sha,
    base_ref = EXCLUDED.base_ref,
    base_sha = EXCLUDED.base_sha,
    merged_at = COALESCE(EXCLUDED.merged_at, pull_requests.merged_at),
    updated_at = now()
RETURNING id, repository_id, number, author, state, head_sha, base_ref, base_sha, merged_at, created_at, updated_at
`

type UpsertPullRequestParams struct {
	RepositoryID int64
	Number       int64
	Author       string
	State        string
	HeadSha      string
	BaseRef      string
	BaseSha      string
	MergedAt     pgtype.Timestamptz
	CreatedAt    pgtype.Timestamptz
}

// PRs observados (guía §3.3): clave natural repo + número/iid en el VCS.
// Upsert idempotente por webhook: el mismo PR re-procesado no duplica fila.
// merged_at usa COALESCE: un evento posterior sin merge no borra el registro.
// created_at es la fecha del PR en el VCS: se mantiene la primera (§3.3).
func (q *Queries) UpsertPullRequest(ctx context.Context, arg UpsertPullRequestParams) (PullRequest, error) {
	row := q.db.QueryRow(ctx, upsertPullRequest,
		arg.RepositoryID,
		arg.Number,
		arg.Author,
		arg.State,
		arg.HeadSha,
		arg.BaseRef,
		arg.BaseSha,
		arg.MergedAt,
		arg.CreatedAt,
	)
	var i PullRequest
	err := row.Scan(
		&i.ID,
		&i.RepositoryID,
		&i.Number,
		&i.Author,
		&i.State,
		&i.HeadSha,
		&i.BaseRef,
		&i.BaseSha,
		&i.MergedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
