// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: repo_index.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countRepoIndexByRepo = `-- name: CountRepoIndexByRepo :one
SELECT COUNT(1) FROM repo_index WHERE repository_id = $1
`

// Chequeo de vacuidad del índice (retrieval: índice vacío → sin contexto).
func (q *Queries) CountRepoIndexByRepo(ctx context.Context, repositoryID int64) (int64, error) {
	row := q.db.QueryRow(ctx, countRepoIndexByRepo, repositoryID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createRepoIndexRow = `-- name: CreateRepoIndexRow :one
INSERT INTO repo_index (repository_id, file, symbol, kind, start_line, end_line, embedding, embedding_model, dims, imports, file_hash)
VALUES ($1, $2, $3, $4, $5, $6, $7::vector, $8, $9, COALESCE($10::text[], '{}'::text[]), $11)
RETURNING id
`

type CreateRepoIndexRowParams struct {
	RepositoryID   int64
	File           string
	Symbol         string
	Kind           string
	StartLine      int32
	EndLine        int32
	Column7        string
	EmbeddingModel string
	Dims           int32
	Column10       []string
	FileHash       string
}

// Una fila por símbolo; el embedding viaja como string con cast a vector.
// NOTA sqlc: el param queda como Column7 (string) — sqlc no infiere nombres
// de params posicionales y el override de sqlc.yaml mapea vector → string.
func (q *Queries) CreateRepoIndexRow(ctx context.Context, arg CreateRepoIndexRowParams) (int64, error) {
	row := q.db.QueryRow(ctx, createRepoIndexRow,
		arg.RepositoryID,
		arg.File,
		arg.Symbol,
		arg.Kind,
		arg.StartLine,
		arg.EndLine,
		arg.Column7,
		arg.EmbeddingModel,
		arg.Dims,
		arg.Column10,
		arg.FileHash,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const deleteRepoIndexByRepo = `-- name: DeleteRepoIndexByRepo :exec

DELETE FROM repo_index WHERE repository_id = $1
`

// repo_index (guía §3.3): índice simbólico RAG por repo. La columna embedding
// jamás aparece en SELECTs (evita el tipo vector en los modelos generados) y
// se INSERTea como literal de texto '[0.1,0.2,...]' con cast ::vector —
// pgvector lo parsea con el input function (§3.3).
// Wipe completo del repo: cambio de modelo de embeddings (§9.6).
func (q *Queries) DeleteRepoIndexByRepo(ctx context.Context, repositoryID int64) error {
	_, err := q.db.Exec(ctx, deleteRepoIndexByRepo, repositoryID)
	return err
}

const deleteRepoIndexByRepoAndFiles = `-- name: DeleteRepoIndexByRepoAndFiles :exec
DELETE FROM repo_index WHERE repository_id = $1 AND file = ANY($2::text[])
`

type DeleteRepoIndexByRepoAndFilesParams struct {
	RepositoryID int64
	Files        []string
}

// Borra los símbolos de los archivos dados antes de re-insertarlos (§9.6).
func (q *Queries) DeleteRepoIndexByRepoAndFiles(ctx context.Context, arg DeleteRepoIndexByRepoAndFilesParams) error {
	_, err := q.db.Exec(ctx, deleteRepoIndexByRepoAndFiles, arg.RepositoryID, arg.Files)
	return err
}

const getRepoIndexDims = `-- name: GetRepoIndexDims :one
SELECT atttypmod AS dims
FROM pg_catalog.pg_attribute
WHERE attrelid = 'repo_index'::regclass
  AND attname = 'embedding'
`

// Dims vigentes desde el catálogo de PG: para el tipo vector, typmod de la
// columna ES la cantidad de dims (§3.3: config nunca diverge del DDL — el
// guard de settings de F4 compara contra esto).
func (q *Queries) GetRepoIndexDims(ctx context.Context) (int32, error) {
	row := q.db.QueryRow(ctx, getRepoIndexDims)
	var dims int32
	err := row.Scan(&dims)
	return dims, err
}

const getRepoIndexEmbeddingModel = `-- name: GetRepoIndexEmbeddingModel :one
SELECT DISTINCT embedding_model
FROM repo_index
WHERE repository_id = $1
LIMIT 1
`

// Modelo vigente del índice: todas las filas del repo comparten modelo —
// distinto al del proveedor actual → wipe + re-index completo (§9.6).
// Índice vacío → pgx.ErrNoRows (el caller decide: primera indexación).
func (q *Queries) GetRepoIndexEmbeddingModel(ctx context.Context, repositoryID int64) (string, error) {
	row := q.db.QueryRow(ctx, getRepoIndexEmbeddingModel, repositoryID)
	var embedding_model string
	err := row.Scan(&embedding_model)
	return embedding_model, err
}

const listRepoIndexByFiles = `-- name: ListRepoIndexByFiles :many
SELECT id, repository_id, file, symbol, kind, start_line, end_line, embedding_model, dims, imports, file_hash, created_at, updated_at
FROM repo_index
WHERE repository_id = $1
  AND file = ANY($2::text[])
`

type ListRepoIndexByFilesParams struct {
	RepositoryID int64
	Files        []string
}

type ListRepoIndexByFilesRow struct {
	ID             int64
	RepositoryID   int64
	File           string
	Symbol         string
	Kind           string
	StartLine      int32
	EndLine        int32
	EmbeddingModel string
	Dims           int32
	Imports        []string
	FileHash       string
	CreatedAt      pgtype.Timestamptz
	UpdatedAt      pgtype.Timestamptz
}

// Todos los símbolos de los archivos dados: insumo de la expansión de un
// salto por el grafo de imports (§3.3).
func (q *Queries) ListRepoIndexByFiles(ctx context.Context, arg ListRepoIndexByFilesParams) ([]ListRepoIndexByFilesRow, error) {
	rows, err := q.db.Query(ctx, listRepoIndexByFiles, arg.RepositoryID, arg.Files)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListRepoIndexByFilesRow
	for rows.Next() {
		var i ListRepoIndexByFilesRow
		if err := rows.Scan(
			&i.ID,
			&i.RepositoryID,
			&i.File,
			&i.Symbol,
			&i.Kind,
			&i.StartLine,
			&i.EndLine,
			&i.EmbeddingModel,
			&i.Dims,
			&i.Imports,
			&i.FileHash,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRepoIndexFiles = `-- name: ListRepoIndexFiles :many
SELECT DISTINCT file, file_hash, embedding_model
FROM repo_index
WHERE repository_id = $1
`

type ListRepoIndexFilesRow struct {
	File           string
	FileHash       string
	EmbeddingModel string
}

// Un renglón por archivo con su hash y modelo: resume-skip de la reindexación
// (§9.6: hash igual y mismo embedding_model → se salta).
func (q *Queries) ListRepoIndexFiles(ctx context.Context, repositoryID int64) ([]ListRepoIndexFilesRow, error) {
	rows, err := q.db.Query(ctx, listRepoIndexFiles, repositoryID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListRepoIndexFilesRow
	for rows.Next() {
		var i ListRepoIndexFilesRow
		if err := rows.Scan(&i.File, &i.FileHash, &i.EmbeddingModel); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchRepoIndexBySimilarity = `-- name: SearchRepoIndexBySimilarity :many
SELECT file, symbol, kind, start_line, end_line, imports
FROM repo_index
WHERE repository_id = $1
  AND file <> $2
ORDER BY embedding <=> $3::vector
LIMIT $4
`

type SearchRepoIndexBySimilarityParams struct {
	RepositoryID   int64
	ExcludeFile    string
	QueryEmbedding string
	RowLimit       int32
}

type SearchRepoIndexBySimilarityRow struct {
	File      string
	Symbol    string
	Kind      string
	StartLine int32
	EndLine   int32
	Imports   []string
}

// Top-K por distancia coseno (§3.3): <=> es la distancia de pgvector — menor
// = más similar. Excluye el archivo bajo revisión (sus símbolos ya están en
// el diff del Reviewer). Sin embedding en el resultado.
func (q *Queries) SearchRepoIndexBySimilarity(ctx context.Context, arg SearchRepoIndexBySimilarityParams) ([]SearchRepoIndexBySimilarityRow, error) {
	rows, err := q.db.Query(ctx, searchRepoIndexBySimilarity,
		arg.RepositoryID,
		arg.ExcludeFile,
		arg.QueryEmbedding,
		arg.RowLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SearchRepoIndexBySimilarityRow
	for rows.Next() {
		var i SearchRepoIndexBySimilarityRow
		if err := rows.Scan(
			&i.File,
			&i.Symbol,
			&i.Kind,
			&i.StartLine,
			&i.EndLine,
			&i.Imports,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
