// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: repositories.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createRepository = `-- name: CreateRepository :one

INSERT INTO repositories (vcs, external_id, owner, name, webhook_secret, secret_token, api_token, base_url, deploy_key)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
RETURNING id, vcs, external_id, owner, name, webhook_secret, secret_token, api_token, base_url, deploy_key, enabled, review_drafts, language, chat_org_only, created_at, updated_at
`

type CreateRepositoryParams struct {
	Vcs           string
	ExternalID    int64
	Owner         string
	Name          string
	WebhookSecret pgtype.Text
	SecretToken   pgtype.Text
	ApiToken      pgtype.Text
	BaseUrl       pgtype.Text
	DeployKey     pgtype.Text
}

// Repos conectados (guía §3.3): CRUD de settings; la desconexión es flag
// (SetRepositoryEnabled), jamás delete (§3.5).
// Los secretos viajan cifrados AES-256-GCM en base64 (§9.2); en GitHub solo
// se completan owner/name — el secret de webhook es global de la App (§9.3).
func (q *Queries) CreateRepository(ctx context.Context, arg CreateRepositoryParams) (Repository, error) {
	row := q.db.QueryRow(ctx, createRepository,
		arg.Vcs,
		arg.ExternalID,
		arg.Owner,
		arg.Name,
		arg.WebhookSecret,
		arg.SecretToken,
		arg.ApiToken,
		arg.BaseUrl,
		arg.DeployKey,
	)
	var i Repository
	err := row.Scan(
		&i.ID,
		&i.Vcs,
		&i.ExternalID,
		&i.Owner,
		&i.Name,
		&i.WebhookSecret,
		&i.SecretToken,
		&i.ApiToken,
		&i.BaseUrl,
		&i.DeployKey,
		&i.Enabled,
		&i.ReviewDrafts,
		&i.Language,
		&i.ChatOrgOnly,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteRepository = `-- name: DeleteRepository :exec
DELETE FROM repositories WHERE id = $1
`

func (q *Queries) DeleteRepository(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteRepository, id)
	return err
}

const getRepository = `-- name: GetRepository :one
SELECT id, vcs, external_id, owner, name, webhook_secret, secret_token, api_token, base_url, deploy_key, enabled, review_drafts, language, chat_org_only, created_at, updated_at FROM repositories WHERE id = $1
`

func (q *Queries) GetRepository(ctx context.Context, id int64) (Repository, error) {
	row := q.db.QueryRow(ctx, getRepository, id)
	var i Repository
	err := row.Scan(
		&i.ID,
		&i.Vcs,
		&i.ExternalID,
		&i.Owner,
		&i.Name,
		&i.WebhookSecret,
		&i.SecretToken,
		&i.ApiToken,
		&i.BaseUrl,
		&i.DeployKey,
		&i.Enabled,
		&i.ReviewDrafts,
		&i.Language,
		&i.ChatOrgOnly,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getRepositoryByVCSExternalID = `-- name: GetRepositoryByVCSExternalID :one
SELECT id, vcs, external_id, owner, name, webhook_secret, secret_token, api_token, base_url, deploy_key, enabled, review_drafts, language, chat_org_only, created_at, updated_at FROM repositories WHERE vcs = $1 AND external_id = $2
`

type GetRepositoryByVCSExternalIDParams struct {
	Vcs        string
	ExternalID int64
}

// Clave natural (vcs, external_id): el webhook resuelve el repo por ella.
func (q *Queries) GetRepositoryByVCSExternalID(ctx context.Context, arg GetRepositoryByVCSExternalIDParams) (Repository, error) {
	row := q.db.QueryRow(ctx, getRepositoryByVCSExternalID, arg.Vcs, arg.ExternalID)
	var i Repository
	err := row.Scan(
		&i.ID,
		&i.Vcs,
		&i.ExternalID,
		&i.Owner,
		&i.Name,
		&i.WebhookSecret,
		&i.SecretToken,
		&i.ApiToken,
		&i.BaseUrl,
		&i.DeployKey,
		&i.Enabled,
		&i.ReviewDrafts,
		&i.Language,
		&i.ChatOrgOnly,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listRepositories = `-- name: ListRepositories :many
SELECT id, vcs, external_id, owner, name, webhook_secret, secret_token, api_token, base_url, deploy_key, enabled, review_drafts, language, chat_org_only, created_at, updated_at FROM repositories ORDER BY owner, name
`

func (q *Queries) ListRepositories(ctx context.Context) ([]Repository, error) {
	rows, err := q.db.Query(ctx, listRepositories)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Repository
	for rows.Next() {
		var i Repository
		if err := rows.Scan(
			&i.ID,
			&i.Vcs,
			&i.ExternalID,
			&i.Owner,
			&i.Name,
			&i.WebhookSecret,
			&i.SecretToken,
			&i.ApiToken,
			&i.BaseUrl,
			&i.DeployKey,
			&i.Enabled,
			&i.ReviewDrafts,
			&i.Language,
			&i.ChatOrgOnly,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setRepositoryEnabled = `-- name: SetRepositoryEnabled :one
UPDATE repositories
SET enabled = $2,
    updated_at = now()
WHERE id = $1
RETURNING id, vcs, external_id, owner, name, webhook_secret, secret_token, api_token, base_url, deploy_key, enabled, review_drafts, language, chat_org_only, created_at, updated_at
`

type SetRepositoryEnabledParams struct {
	ID      int64
	Enabled bool
}

// Desconexión como flag, sin delete (§3.5).
func (q *Queries) SetRepositoryEnabled(ctx context.Context, arg SetRepositoryEnabledParams) (Repository, error) {
	row := q.db.QueryRow(ctx, setRepositoryEnabled, arg.ID, arg.Enabled)
	var i Repository
	err := row.Scan(
		&i.ID,
		&i.Vcs,
		&i.ExternalID,
		&i.Owner,
		&i.Name,
		&i.WebhookSecret,
		&i.SecretToken,
		&i.ApiToken,
		&i.BaseUrl,
		&i.DeployKey,
		&i.Enabled,
		&i.ReviewDrafts,
		&i.Language,
		&i.ChatOrgOnly,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateRepository = `-- name: UpdateRepository :one
UPDATE repositories
SET owner = $2,
    name = $3,
    webhook_secret = $4,
    secret_token = $5,
    api_token = $6,
    base_url = $7,
    deploy_key = $8,
    review_drafts = $9,
    language = $10,
    chat_org_only = $11,
    updated_at = now()
WHERE id = $1
RETURNING id, vcs, external_id, owner, name, webhook_secret, secret_token, api_token, base_url, deploy_key, enabled, review_drafts, language, chat_org_only, created_at, updated_at
`

type UpdateRepositoryParams struct {
	ID            int64
	Owner         string
	Name          string
	WebhookSecret pgtype.Text
	SecretToken   pgtype.Text
	ApiToken      pgtype.Text
	BaseUrl       pgtype.Text
	DeployKey     pgtype.Text
	ReviewDrafts  bool
	Language      string
	ChatOrgOnly   bool
}

// Config editable desde settings; enabled va por SetRepositoryEnabled. vcs y
// external_id son identidad: no se editan.
func (q *Queries) UpdateRepository(ctx context.Context, arg UpdateRepositoryParams) (Repository, error) {
	row := q.db.QueryRow(ctx, updateRepository,
		arg.ID,
		arg.Owner,
		arg.Name,
		arg.WebhookSecret,
		arg.SecretToken,
		arg.ApiToken,
		arg.BaseUrl,
		arg.DeployKey,
		arg.ReviewDrafts,
		arg.Language,
		arg.ChatOrgOnly,
	)
	var i Repository
	err := row.Scan(
		&i.ID,
		&i.Vcs,
		&i.ExternalID,
		&i.Owner,
		&i.Name,
		&i.WebhookSecret,
		&i.SecretToken,
		&i.ApiToken,
		&i.BaseUrl,
		&i.DeployKey,
		&i.Enabled,
		&i.ReviewDrafts,
		&i.Language,
		&i.ChatOrgOnly,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
