// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: reviews.sql

package store

import (
	"context"
)

const createReview = `-- name: CreateReview :one

INSERT INTO reviews (pull_request_id, head_sha, base_sha)
VALUES ($1, $2, $3)
RETURNING id, pull_request_id, head_sha, base_sha, summary, walkthrough, mermaid, status, created_at, updated_at
`

type CreateReviewParams struct {
	PullRequestID int64
	HeadSha       string
	BaseSha       string
}

// Reviews (guía §3.3): una por corrida; head_sha + base_sha son la identidad
// de la corrida (§3.6).
// Nace running con textos vacíos: summary/walkthrough/mermaid se completan al
// finalizar la corrida.
func (q *Queries) CreateReview(ctx context.Context, arg CreateReviewParams) (Review, error) {
	row := q.db.QueryRow(ctx, createReview, arg.PullRequestID, arg.HeadSha, arg.BaseSha)
	var i Review
	err := row.Scan(
		&i.ID,
		&i.PullRequestID,
		&i.HeadSha,
		&i.BaseSha,
		&i.Summary,
		&i.Walkthrough,
		&i.Mermaid,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getLatestReviewByPR = `-- name: GetLatestReviewByPR :one
SELECT id, pull_request_id, head_sha, base_sha, summary, walkthrough, mermaid, status, created_at, updated_at FROM reviews
WHERE pull_request_id = $1
ORDER BY id DESC
LIMIT 1
`

// Última corrida del PR: el id es monotónico, ordenar por id DESC es estable.
func (q *Queries) GetLatestReviewByPR(ctx context.Context, pullRequestID int64) (Review, error) {
	row := q.db.QueryRow(ctx, getLatestReviewByPR, pullRequestID)
	var i Review
	err := row.Scan(
		&i.ID,
		&i.PullRequestID,
		&i.HeadSha,
		&i.BaseSha,
		&i.Summary,
		&i.Walkthrough,
		&i.Mermaid,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getReview = `-- name: GetReview :one
SELECT id, pull_request_id, head_sha, base_sha, summary, walkthrough, mermaid, status, created_at, updated_at FROM reviews WHERE id = $1
`

func (q *Queries) GetReview(ctx context.Context, id int64) (Review, error) {
	row := q.db.QueryRow(ctx, getReview, id)
	var i Review
	err := row.Scan(
		&i.ID,
		&i.PullRequestID,
		&i.HeadSha,
		&i.BaseSha,
		&i.Summary,
		&i.Walkthrough,
		&i.Mermaid,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateReviewStatus = `-- name: UpdateReviewStatus :one
UPDATE reviews
SET status = $2,
    updated_at = now()
WHERE id = $1
RETURNING id, pull_request_id, head_sha, base_sha, summary, walkthrough, mermaid, status, created_at, updated_at
`

type UpdateReviewStatusParams struct {
	ID     int64
	Status string
}

// success/partial/stale/failed según el desenlace (§3.3).
func (q *Queries) UpdateReviewStatus(ctx context.Context, arg UpdateReviewStatusParams) (Review, error) {
	row := q.db.QueryRow(ctx, updateReviewStatus, arg.ID, arg.Status)
	var i Review
	err := row.Scan(
		&i.ID,
		&i.PullRequestID,
		&i.HeadSha,
		&i.BaseSha,
		&i.Summary,
		&i.Walkthrough,
		&i.Mermaid,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateReviewSummary = `-- name: UpdateReviewSummary :one
UPDATE reviews
SET summary = $2,
    walkthrough = $3,
    mermaid = $4,
    updated_at = now()
WHERE id = $1
RETURNING id, pull_request_id, head_sha, base_sha, summary, walkthrough, mermaid, status, created_at, updated_at
`

type UpdateReviewSummaryParams struct {
	ID          int64
	Summary     string
	Walkthrough string
	Mermaid     string
}

func (q *Queries) UpdateReviewSummary(ctx context.Context, arg UpdateReviewSummaryParams) (Review, error) {
	row := q.db.QueryRow(ctx, updateReviewSummary,
		arg.ID,
		arg.Summary,
		arg.Walkthrough,
		arg.Mermaid,
	)
	var i Review
	err := row.Scan(
		&i.ID,
		&i.PullRequestID,
		&i.HeadSha,
		&i.BaseSha,
		&i.Summary,
		&i.Walkthrough,
		&i.Mermaid,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
