// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users.sql

package store

import (
	"context"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (username, role, password_hash, must_change_password)
VALUES ($1, $2, $3, $4)
RETURNING id, username, role, password_hash, must_change_password, disabled, created_at, updated_at
`

type CreateUserParams struct {
	Username           string
	Role               string
	PasswordHash       string
	MustChangePassword bool
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.Username,
		arg.Role,
		arg.PasswordHash,
		arg.MustChangePassword,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Role,
		&i.PasswordHash,
		&i.MustChangePassword,
		&i.Disabled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getByUsername = `-- name: GetByUsername :one
SELECT id, username, role, password_hash, must_change_password, disabled, created_at, updated_at FROM users WHERE username = $1
`

func (q *Queries) GetByUsername(ctx context.Context, username string) (User, error) {
	row := q.db.QueryRow(ctx, getByUsername, username)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Role,
		&i.PasswordHash,
		&i.MustChangePassword,
		&i.Disabled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
