// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: webhook_deliveries.sql

package store

import (
	"context"
)

const createWebhookDelivery = `-- name: CreateWebhookDelivery :one

INSERT INTO webhook_deliveries (vcs, delivery_id)
VALUES ($1, $2)
ON CONFLICT (vcs, delivery_id) DO NOTHING
RETURNING id, vcs, delivery_id, created_at
`

type CreateWebhookDeliveryParams struct {
	Vcs        string
	DeliveryID string
}

// Dedup de webhooks (guía §3.3): delivery IDs ya procesados.
// Idempotente: solo la primera entrega inserta y devuelve la fila; en
// duplicado ON CONFLICT no devuelve filas (pgx: pgx.ErrNoRows = ya procesado).
func (q *Queries) CreateWebhookDelivery(ctx context.Context, arg CreateWebhookDeliveryParams) (WebhookDelivery, error) {
	row := q.db.QueryRow(ctx, createWebhookDelivery, arg.Vcs, arg.DeliveryID)
	var i WebhookDelivery
	err := row.Scan(
		&i.ID,
		&i.Vcs,
		&i.DeliveryID,
		&i.CreatedAt,
	)
	return i, err
}

const webhookDeliveryExists = `-- name: WebhookDeliveryExists :one
SELECT EXISTS (
    SELECT 1 FROM webhook_deliveries
    WHERE vcs = $1 AND delivery_id = $2
)
`

type WebhookDeliveryExistsParams struct {
	Vcs        string
	DeliveryID string
}

func (q *Queries) WebhookDeliveryExists(ctx context.Context, arg WebhookDeliveryExistsParams) (bool, error) {
	row := q.db.QueryRow(ctx, webhookDeliveryExists, arg.Vcs, arg.DeliveryID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}
